#!/usr/bin/env python3
#
# udict -- Look something up on
# urbandictionary.com
#
#
#
#
#
#
#
#

import sys
import re
from http.client import HTTPConnection


INPUT = sys.argv[1:]

# If nothing is given in the command line; read from stdin.
if len(INPUT)==0:
    for line in sys.stdin:
        INPUT += line.split()

# Convert list to str
# and if more than one word is given
# they're joined with a +
INPUT = '+'.join(INPUT)

# Create search url
search = "/define.php?term="+INPUT

# Connect to acronymfinder.com and request result.
conn = HTTPConnection("www.urbandictionary.com")
conn.request("GET", search)

resp = conn.getresponse()
if resp.status != 200:
    print("Server responded with error code %d." % (resp.status))
    sys.exit(1)

# Save response
res = resp.read().decode('utf-8')
conn.close()

# Parse the result
resblock = re.search("cont.*>.*hidden-phone", res, re.DOTALL)

meaning = re.findall("definition\'>\n[A-Z].*\n</div>", resblock.group())
example = re.findall("example\'>\n.*\n</div>", resblock.group())

# Remove unnecessary chars
for k in range(0, len(meaning)):
    meaning[k] = re.search("[A-Z].*[a-z]", meaning[k]).group()
    #meaning[k] = meaning[k].replace('</a></td><td', '')
    #meaning[k] = meaning[k].replace('</td><td', '')

#for j in range(0, len(example)):
#    example[j] = re.search('', example[j]).group()

# Set the printing to max 10
if len(meaning) > 10:
    anz=10
else:
    anz=len(meaning)

# Print the result
print("\n'%s' is used as followed:\n" % (INPUT.replace('+', ' ')))
for i in range(0, anz):
    print("%d:  %s" % (i+1, meaning[i]))
