#!/usr/bin/env python3
#
# udict -- Look something up on
# urbandictionary.com
#
#
#
#
#
#
#
#

import sys
import re
from http.client import HTTPConnection


INPUT = sys.argv[1:]

# If nothing is given in the command line; read from stdin.
if len(INPUT)==0:
    for line in sys.stdin:
        INPUT += line.split()

# Convert list to str
# and if more than one word is given
# they're joined with a +
INPUT = '+'.join(INPUT)

# Create search url
search = "/define.php?term="+INPUT

# Connect to acronymfinder.com and request result.
conn = HTTPConnection("www.urbandictionary.com")
conn.request("GET", search)

resp = conn.getresponse()
if resp.status != 200:
    print("Server responded with error code %d." % (resp.status))
    sys.exit(1)

# Save response
res = resp.read().decode('utf-8')
conn.close()

# Parse the result
resblock = re.search("id='cont.*>.*copyright", res, re.DOTALL)

meaning = re.findall("meaning'>\n[A-Za-z].*?<div class='example", resblock.group(), re.DOTALL)
#example = re.findall("example\'>\n.*\n</div>", resblock.group())

# Remove unnecessary chars
for k in range(0, len(meaning)):
    meaning[k] = meaning[k].lstrip("meaning'>\n")
    #meaning[k] = re.search("[A-Za-z].*[a-z]", meaning[k], re.DOTALL).group()
    meaning[k] = meaning[k].replace('<br/>', '    ')
    meaning[k] = meaning[k].rstrip('</div>\n<div class=\'example')
    meaning[k] = meaning[k].replace("<a href=\"", '( ')
    meaning[k] = meaning[k].replace("\">", ' ) ')
    meaning[k] = meaning[k].replace("</a>", '')
    meaning[k] = meaning[k].replace("\r", '')
    meaning[k] = meaning[k].replace("&#39;", "'")   # latin-1 ' into utf-8 '
    meaning[k] = meaning[k].replace("&quot;", "\"") # latin-1 " into utf-8 "
    #meaning[k] = meaning[k].replace(str(re.search("<a href=\".*\">", meaning[k], re.DOTALL)), "")

#for j in range(0, len(example)):
#    example[j] = re.search('', example[j]).group()

# Set the printing to max 10
if len(meaning) > 10:
    anz=10
else:
    anz=len(meaning)

# Print the result
print("\n'%s' is used as followed:\n" % (INPUT.replace('+', ' ')))
for i in range(0, anz):
    print("%d:  %s\n" % (i+1, meaning[i]))
